import dev.detekt.gradle.extensions.DetektExtension
import org.gradle.language.base.plugins.LifecycleBasePlugin
import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import kotlinx.kover.gradle.plugin.dsl.GroupingEntityType
import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.kover)
}

allprojects {
    group = "app.getknit.spool"
    // Overridable from the command line so a tagged release stamps the tag into the distribution
    // archive names and the image labels: `./gradlew -PspoolVersion=1.2.3 :daemon:distTar`.
    // Everything else — local builds, CI on a branch — stays a SNAPSHOT, which is the honest label
    // for a build that is not a release.
    //
    // The number itself still has to move by hand after each release, and it is the one part of
    // this that can rot: a SNAPSHOT trailing the newest release is worse than no version at all.
    // `0.1.0-SNAPSHOT` on a main build cut after 0.2.0 reads as *older* than the release it
    // supersedes — backwards for the one question `GET /source` exists to answer. BuildInfoTest
    // pins it against CHANGELOG.md so the bump fails the build instead of being forgotten.
    version = (findProperty("spoolVersion") as String?)?.takeIf { it.isNotBlank() } ?: "0.4.0-SNAPSHOT"
}

// ---- coverage ----
// Kover, measured across all three modules and reported once from the root. Merging matters here
// because the modules test each other: :protocol's records and digest are driven hardest by
// :daemon's server tests, and only a merged report credits those lines to :protocol.
//
//   ./gradlew koverHtmlReport         merged, human-readable: build/reports/kover/html/index.html
//   ./gradlew koverXmlReport          merged JaCoCo-format XML, what both CIs report from
//   ./gradlew koverLog                one line on stdout, what GitLab CI's coverage regex reads
//   ./gradlew koverVerify             enforces the floors below
//   ./gradlew :daemon:koverHtmlReport one module on its own
//
// The root-project tasks above are the merged report; the same names qualified with a module path
// report that module alone. Nothing is wired to `check` on purpose — `check` is the pre-MR gate
// and stays a compile+lint+test run.
//
// :conformance's checks are credited by the merged report only: :daemon's ConformanceSelfTest
// runs the whole suite against an in-process server, and the agent counts every class the test
// JVM loads, whichever module's jar it came from. So `:conformance:koverHtmlReport` on its own
// reads a few percent — that module's own tests cover only the report and the failure
// describer — and the merged number is the one to read. The conformance-selftest CI job still
// runs the same suite against the packaged binaries, out of process; it proves the artefacts and
// the CLI entry points, not lines.
//
// The floors are ratchets, not aspirations: a few points under what the suite covers today (line
// 97%, branch 76%), so an unrelated refactor does not fail the build but deleting tests does.
// Raise them when coverage rises; do not lower them to make a red build green.
val coverageFloorLine = 94
val coverageFloorBranch = 73

val coverageExcludedClasses =
    listOf(
        // Generated by kotlinx-serialization, not written or reviewed here. Its uncovered
        // branches are decoder paths for wire shapes the records forbid.
        "*\$serializer",
        // Process entry points: argument parsing, env wiring, and a shutdown hook, all reachable
        // only by starting a real process. The conformance-selftest job covers them for real, out
        // of process, where Kover cannot see it — counting them here would just be permanently-red
        // lines that no unit test can legitimately reach. Only the `exitProcess` paths live in
        // these files; the conformance runner itself (Suite.kt) is called in-process and counted.
        //
        // The trailing `*` is load-bearing: it takes the lambda classes the compiler synthesizes
        // inside `main` (`MainKt$main$…`), which an exact name leaves behind.
        //
        // Not excluded, and not expected to turn green: SpoolServer's ping-timeout swallow (Ktor's
        // pinger is fixed at 30 s/60 s), its slow-consumer close (needs the outgoing channel and
        // the loopback TCP buffers full), the `start()` default-argument bridge, and the
        // missing-field branches kotlinx-serialization synthesizes on `@Serializable` classes.
        "app.getknit.spool.MainKt*",
        "app.getknit.spool.conformance.MainKt*",
    )

dependencies {
    kover(project(":protocol"))
    kover(project(":daemon"))
    kover(project(":conformance"))
}

kover {
    reports {
        filters {
            excludes {
                classes(coverageExcludedClasses)
            }
        }

        total {
            html {
                title = "knit-spool coverage"
                onCheck = false
            }

            xml {
                onCheck = false
            }

            log {
                onCheck = false
                header = "knit-spool"
                // The `coverage:` regex in .gitlab-ci.yml matches this exact wording. GitHub
                // Actions parses build/reports/kover/report.xml instead, so it is unaffected.
                format = "Total line coverage: <value>%"
                groupBy = GroupingEntityType.APPLICATION
                coverageUnits = CoverageUnit.LINE
                aggregationForGroup = AggregationType.COVERED_PERCENTAGE
            }

            verify {
                onCheck = false
                rule("line coverage") {
                    minBound(coverageFloorLine, CoverageUnit.LINE, AggregationType.COVERED_PERCENTAGE)
                }
                rule("branch coverage") {
                    minBound(coverageFloorBranch, CoverageUnit.BRANCH, AggregationType.COVERED_PERCENTAGE)
                }
            }
        }
    }
}

// The same exclusions on each module's own report, so `:daemon:koverHtmlReport` and the merged
// report agree about what is being counted. Filters do not inherit from the root — without this a
// single-module report silently counts entry points the merged one drops, and the two numbers
// disagree for a reason nobody can see.
subprojects {
    pluginManager.withPlugin("org.jetbrains.kotlinx.kover") {
        extensions.configure<KoverProjectExtension>("kover") {
            reports {
                filters {
                    excludes {
                        classes(coverageExcludedClasses)
                    }
                }
            }
        }
    }
}

// ---- static analysis ----
// detekt, applied per module (like ktlint) and configured once here so the three modules cannot
// drift. `config/detekt/detekt.yml` is an overlay on detekt's bundled defaults, not a full config:
// it lists only the rules whose defaults misfire on this codebase, with a reason each, and
// everything else keeps the default. The same shape as the Knit app repo's overlay, on the same
// detekt version, so a rule that is tuned there reads the same here.
//
//   ./gradlew detektMain detektTest   every module, with type resolution; what `check` (and so
//                                     both CIs) runs. Reports under <module>/build/reports/detekt/
//                                     as main.* and test.* (html for a person, sarif and
//                                     checkstyle xml for tooling)
//   ./gradlew :daemon:detektMain      one module, one compilation
//   ./gradlew detekt                  every module, WITHOUT type resolution: no compile first, so
//                                     the quick local pass — but the rules that need types stay
//                                     silent, which is why `check` does not run this one
//
// The defaults the overlay sits on are detekt-core's default-detekt-config.yml at the pinned tag:
// https://github.com/detekt/detekt/blob/v2.0.0-alpha.6/detekt-core/src/main/resources/default-detekt-config.yml
//
// Gating, not advisory, for the same reason ktlint is: the codebase is clean against this rule set
// and the version is pinned, so a new finding is a real change to the code under review, not a
// drift in the tool.
//
// Type resolution comes from the per-compilation tasks: the plugin hands `detektMain` and
// `detektTest` the same classpath, language version and friend paths as the Kotlin compile task
// they shadow, so rules that reason about types — unused declarations, an `!!` on a nullable, a
// `?: emptyList()` that is `orEmpty()`, a parameter list counted without its defaults — run for
// real. The plugin wires only the plain `detekt` task into `check`, so this swaps it out: keeping
// both would run every non-type rule twice and report each finding twice.
subprojects {
    pluginManager.withPlugin("dev.detekt") {
        extensions.configure<DetektExtension>("detekt") {
            buildUponDefaultConfig = true
            config.setFrom(rootProject.layout.projectDirectory.file("config/detekt/detekt.yml"))
            // Report paths relative to the repo root rather than the module, so a SARIF location
            // is the path a diff annotator expects.
            basePath = rootProject.layout.projectDirectory
        }
        // `named(Spec)` rather than `matching`: it filters by name without realising every task,
        // and it does not care whether `check` exists yet.
        tasks.named { it == LifecycleBasePlugin.CHECK_TASK_NAME }.configureEach {
            // Registered after the plugin's own `dependsOn(detekt)`, so this sees it and drops it.
            setDependsOn(dependsOn.filterNot { it is TaskProvider<*> && it.name == "detekt" })
            dependsOn("detektMain", "detektTest")
        }
    }
}
