import kotlinx.kover.gradle.plugin.dsl.AggregationType
import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import kotlinx.kover.gradle.plugin.dsl.GroupingEntityType
import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension

plugins {
    alias(libs.plugins.kotlin.jvm) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ktlint) apply false
    alias(libs.plugins.kover)
}

allprojects {
    group = "app.getknit.spool"
    version = "0.1.0-SNAPSHOT"
}

// ---- coverage ----
// Kover, measured across all three modules and reported once from the root. Merging matters here
// because the modules test each other: :protocol's records and digest are driven hardest by
// :daemon's server tests, and only a merged report credits those lines to :protocol.
//
//   ./gradlew koverHtmlReport         merged, human-readable: build/reports/kover/html/index.html
//   ./gradlew koverXmlReport          merged JaCoCo-format XML, what both CIs report from
//   ./gradlew koverLog                one line on stdout, what GitLab CI's coverage regex reads
//   ./gradlew koverVerify             enforces the floors below
//   ./gradlew :daemon:koverHtmlReport one module on its own
//
// The root-project tasks above are the merged report; the same names qualified with a module path
// report that module alone. Nothing is wired to `check` on purpose — `check` is the pre-MR gate
// and stays a compile+lint+test run.
//
// Read the total with one caveat: it sits well below the per-module numbers (:protocol 98%,
// :daemon 91%) because :conformance's check bodies only execute against a live server, which
// happens in the conformance-selftest CI job — a separate process, which Kover does not
// instrument. So a change to :daemon or :protocol is judged by the merged report; a change to
// :conformance is judged by whether the selftest still passes.
//
// The floors are ratchets, not aspirations: a few points under what the suite covers today (line
// 60%, branch 54%), so an unrelated refactor does not fail the build but deleting tests does.
// Raise them when coverage rises; do not lower them to make a red build green.
val coverageFloorLine = 57
val coverageFloorBranch = 51

val coverageExcludedClasses =
    listOf(
        // Generated by kotlinx-serialization, not written or reviewed here. Its uncovered
        // branches are decoder paths for wire shapes the records forbid.
        "*\$serializer",
        // Process entry points: argument parsing, env wiring, and a shutdown hook, all reachable
        // only by starting a real process. The conformance-selftest job covers them for real, out
        // of process, where Kover cannot see it — counting them here would just be permanently-red
        // lines that no unit test can legitimately reach.
        //
        // The trailing `*` is load-bearing: it takes the lambda classes the compiler synthesizes
        // inside `main` (`MainKt$main$…`), which an exact name leaves behind.
        "app.getknit.spool.MainKt*",
        "app.getknit.spool.conformance.MainKt*",
    )

dependencies {
    kover(project(":protocol"))
    kover(project(":daemon"))
    kover(project(":conformance"))
}

kover {
    reports {
        filters {
            excludes {
                classes(coverageExcludedClasses)
            }
        }

        total {
            html {
                title = "knit-spool coverage"
                onCheck = false
            }

            xml {
                onCheck = false
            }

            log {
                onCheck = false
                header = "knit-spool"
                // The `coverage:` regex in .gitlab-ci.yml matches this exact wording. GitHub
                // Actions parses build/reports/kover/report.xml instead, so it is unaffected.
                format = "Total line coverage: <value>%"
                groupBy = GroupingEntityType.APPLICATION
                coverageUnits = CoverageUnit.LINE
                aggregationForGroup = AggregationType.COVERED_PERCENTAGE
            }

            verify {
                onCheck = false
                rule("line coverage") {
                    minBound(coverageFloorLine, CoverageUnit.LINE, AggregationType.COVERED_PERCENTAGE)
                }
                rule("branch coverage") {
                    minBound(coverageFloorBranch, CoverageUnit.BRANCH, AggregationType.COVERED_PERCENTAGE)
                }
            }
        }
    }
}

// The same exclusions on each module's own report, so `:daemon:koverHtmlReport` and the merged
// report agree about what is being counted. Filters do not inherit from the root — without this a
// single-module report silently counts entry points the merged one drops, and the two numbers
// disagree for a reason nobody can see.
subprojects {
    pluginManager.withPlugin("org.jetbrains.kotlinx.kover") {
        extensions.configure<KoverProjectExtension>("kover") {
            reports {
                filters {
                    excludes {
                        classes(coverageExcludedClasses)
                    }
                }
            }
        }
    }
}
